### ISSUE TITLE
Unable to add .torrent files via webui

### ISSUE THREAD

**Issue by Steve-Brule** [hotio/rflood#3]
When trying to add a torrent with a torrent file it fails, even when using flood directly, not through a reverse proxy. Here's the error message (in browser's f12): {"code":-32602,"message":"invalid parameters: unexpected data type"}. The container log shows this (the only relevant line): POST /api/torrents/add-files 500 60.017 ms - 68.

Tested with multiple ubuntu .torrent files (less than 1mb in size). These same files work correctly in an instance of transmission on the same host.

I tried firefox 93.0, edge 95.0.1020.40, safari 14.0.2 (mobile). Using this version of the container: hotio/rflood:release-490fa07 on a debian 11 host, docker-ce version 5:20.10.10~3-0~debian-bullseye.

I have tried altering the xmlrpc variable in rtorrent.rc to no avail; I have also tried this with vpn enabled and disabled, the result was the same. I have checked several times and the GUID/PUID are configured to be able to rw the /config folder as well as the download folder. Magnet links work without issue.

Thank you in advance.

**Comment by Steve-Brule** [comment]
Is this the wrong place for this issue? Or is the issue not properly formatted?

**Comment by mrhotio** [comment]
You're asking support for the application, so this is definately the wrong place for that
